services:
  mongo:
    image: mongo:latest
    container_name: k8sdb
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: k8sbackend
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mongodb://k8sdb:27017/k8s_db
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data_db:
