# Creating Backend Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: backendnamespace
---
# Creating Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backendnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: doomerdpk/k8s_fullstack-backend:dotenv
          ports:
            - containerPort: 3000
          env:
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: port
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/app/secrets"
      volumes:
        - name: env-file
          secret:
            secretName: backend-secret

---
# Creating Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backendnamespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
