apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontendnamespace
spec:
  # ingressClassName: nginx
  ingressClassName: haproxy
  rules:
    - host: k8s.deepak.cfd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backendnamespace
spec:
  # ingressClassName: nginx
  ingressClassName: haproxy
  rules:
    - host: k8s.deepak.cfd
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
